### ISSUE TITLE
djangobook.net link doesn't work anymore

### ISSUE THREAD

**Issue by FahimFBA** [masnun/django-bangla-book#2]
**http://djangobook.net link doesn't work anymore.** 
Browser kept on showing this too:

> error resolving "djangobook.net:80""/" ("") for "10.238.5.122": rpc error: code = Unknown desc = no such record

**Comment by m4hi2** [comment]
@FahimFBA it's an abandoned project. The last update is almost 8 years old.

**Comment by FahimFBA** [comment]
I see. Thanks for the reminder, brother, @m4hi2
